# Site settings
title: Henry Jekyll

# Build settings
markdown: kramdown
permalink: pretty

favicon: "/assets/img/temp_chem.jpg"

port: 3000
url: http://localhost:3000

sass:
  sass_dir: assets/css
  style: :nested

# Add bibliography
gems: ['jekyll/scholar']

scholar:
  style: assets/bib/_ieee-with-url.csl
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: assets/bib
  bibliography: _mybib.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex
  - HTML

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
