module Preamble where

frontmatter = "\\documentclass[12pt]{article}\n\\usepackage{haskell}\n\\usepackage{enumerate}\n\\usepackage{multicol}\n\\setlength{\\topmargin}{-0.5in}\n\\setlength{\\textheight}{9.0in}\n"
     ++ "\\setlength{\\textwidth}{7.5in}\n"
     ++ "\\setlength{\\oddsidemargin}{-0.5in}\n"
     ++ "%\\setlength{\\evensidemargin}{-0.1in}\n"
     ++ "\\setlength{\\parindent}{0mm}\n"
     ++ "\\setlength{\\parskip}{0.1in}\n"
     ++ "%\\renewcommand{\\date}{Dec. 17, 2014}\n"
     ++ "\\newcommand{\\forget}[1]{}\n"
     ++ "% new itemize environment with itemsep parameter\n"
     ++ "\\newenvironment{myitemize}[1][0]\n"
     ++ "  { \\begin{itemize}\n"
     ++ "    % set spacing between items\n"
     ++ "    \\addtolength{\\itemsep}{#1\\baselineskip}\n"
     ++ "    % set spacing between lines\n"
     ++ "    \\addtolength{\\baselineskip}{#1\\baselineskip} }\n"
     ++ "  { \\end{itemize} }\n"
     ++ "\n"
     ++ "\\newenvironment{myenumerate}[1][0]\n"
     ++ "  { \\begin{enumerate}\n"
     ++ "    % set spacing between items\n"
     ++ "    \\addtolength{\\itemsep}{#1\\baselineskip}\n"
     ++ "    % set spacing between lines\n"
     ++ "    \\addtolength{\\baselineskip}{#1\\baselineskip} }\n"
     ++ "  { \\end{enumerate} }\n"
     ++ "\n"
     ++ "\n"
     ++ "\\newcommand{\\ra}{\\ensuremath{\\rightarrow}}\n"
     ++ "  \n"
     ++ "    \n"
     ++ "\\pagestyle{empty}\n"
     ++ "%\\pagenumbering{nopagenumbering}\n"
     ++ "\\usepackage{datetime}\n"
     ++ "\\newdate{date}{12}{12}{2016}\n"
     ++ "\\usdate\n"
     ++ "%\\thispagestyle{empty}\n"
     ++ "\\begin{document}\n"
     ++ " \n"
     ++ "\\title{\\vspace{10ex}CS4450/7450 Final\\\\Fall 2016\\\\ \\date{\\displaydate{date}}}\n"
     ++ "\n"
     ++ "\\maketitle\n"
     ++ "{\\Large\n"
     ++ "\\begin{flushleft}\n"
     ++ "{\\bf Name:}\\\\\n"
     ++ "{\\bf Student Number:}\n"
     ++ "\\end{flushleft}\n"
     ++ "}\n"
     ++ "\\vfill\n"
     ++ "\n"
     ++ "\\thispagestyle{empty}\n"
     ++ "\n"
     ++ "\n"
     ++ "{\\large\n"
     ++ "\\begin{center}\n"
     ++ "\\begin{minipage}{4.5in}\n"
     ++ "\\begin{itemize}\n"
     ++ "\\item This is a closed book, closed note exam.\n"
     ++ "\\item You may not use a calculator or similar device.\n"
     ++ "\\item There are 49 problems, worth 100 points total.\n"
     ++ "\\item Unless otherwise noted, each question is worth 2 points.\n"
     ++ "\\end{itemize}\n"
     ++ "\\end{minipage}\n"
     ++ "\\end{center}\n"
     ++ "}\n"
     ++ "\n"
     ++ "\\pagebreak\n"
     ++ "\n"
     ++ "\\begin{enumerate}"
     
endmatter = "\\end{enumerate}\n" ++ "\\end{document}\n"
